-- USER SQL
CREATE USER "ORAMON_STATS" IDENTIFIED BY "telefon3"  
DEFAULT TABLESPACE "SYSAUX"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "ORAMON_STATS" QUOTA UNLIMITED ON "SYSAUX";

-- ROLES

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO "ORAMON_STATS" ;
GRANT CREATE TRIGGER TO "ORAMON_STATS" ;
GRANT CREATE MATERIALIZED VIEW TO "ORAMON_STATS" ;
GRANT CREATE DIMENSION TO "ORAMON_STATS" ;
GRANT CREATE OPERATOR TO "ORAMON_STATS" ;
GRANT CREATE INDEXTYPE TO "ORAMON_STATS" ;
GRANT CREATE VIEW TO "ORAMON_STATS" ;
GRANT CREATE SESSION TO "ORAMON_STATS" ;
GRANT CREATE TABLE TO "ORAMON_STATS" ;
GRANT CREATE TYPE TO "ORAMON_STATS" ;
GRANT CREATE SYNONYM TO "ORAMON_STATS" ;
GRANT CREATE SEQUENCE TO "ORAMON_STATS" ;
GRANT EXECUTE DYNAMIC MLE TO "ORAMON_STATS" ;
GRANT CREATE CLUSTER TO "ORAMON_STATS" ;
GRANT CREATE PROCEDURE TO "ORAMON_STATS" ;

