-- USER SQL
CREATE USER "ORAMON" IDENTIFIED BY "telefon3"
DEFAULT TABLESPACE "APEX"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "ORAMON" QUOTA UNLIMITED ON "APEX";

-- ROLES

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO "ORAMON" ;
GRANT CREATE TRIGGER TO "ORAMON" ;
GRANT CREATE MATERIALIZED VIEW TO "ORAMON" ;
GRANT CREATE DIMENSION TO "ORAMON" ;
GRANT CREATE OPERATOR TO "ORAMON" ;
GRANT CREATE INDEXTYPE TO "ORAMON" ;
GRANT CREATE VIEW TO "ORAMON" ;
GRANT CREATE SESSION TO "ORAMON" ;
GRANT CREATE TABLE TO "ORAMON" ;
GRANT CREATE TYPE TO "ORAMON" ;
GRANT CREATE SYNONYM TO "ORAMON" ;
GRANT CREATE SEQUENCE TO "ORAMON" ;
--GRANT EXECUTE DYNAMIC MLE TO "ORAMON" ;
GRANT CREATE CLUSTER TO "ORAMON" ;
GRANT CREATE PROCEDURE TO "ORAMON" ;
GRANT CREATE DATABASE LINK TO "ORAMON";
