-- USER SQL
CREATE USER PERFSTAT IDENTIFIED BY "oracle"
DEFAULT TABLESPACE "SYSAUX"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER PERFSTAT QUOTA UNLIMITED ON "SYSAUX";

-- ROLES
GRANT "SELECT_CATALOG_ROLE" TO PERFSTAT ;
ALTER USER PERFSTAT DEFAULT ROLE "SELECT_CATALOG_ROLE";

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO PERFSTAT ;
GRANT ALTER SESSION TO PERFSTAT ;
GRANT CREATE VIEW TO PERFSTAT ;
GRANT CREATE SESSION TO PERFSTAT ;
GRANT CREATE TABLE TO PERFSTAT ;
GRANT CREATE PUBLIC SYNONYM TO PERFSTAT ;
GRANT CREATE SEQUENCE TO PERFSTAT ;
GRANT DROP PUBLIC SYNONYM TO PERFSTAT ;
GRANT CREATE PROCEDURE TO PERFSTAT ;
