
  CREATE DATABASE LINK "XEPDB1_DROPLET"
   USING '(DESCRIPTION=
   (ADDRESS=
   (PROTOCOL=TCP)
   (HOST=46.101.137.47)
   (PORT=1521))
   (CONNECT_DATA=
     (SERVER=DEDICATED)
     (SERVICE_NAME=XEPDB1)
   )
)'