  CREATE TABLE "ORAMON"."ORAMON_TOP_SQL" 
   (	"SNAP_ID" NUMBER NOT NULL ENABLE,
	"LAST_ACTIVE_TIME" DATE,
	"SQL_ID" VARCHAR2(13),
	"TEXT_SUBSET" VARCHAR2(31) NOT NULL ENABLE,
	"EXECUTIONS" NUMBER,
	"APPLICATION_WAIT_TIME" NUMBER,
	"CONCURRENCY_WAIT_TIME" NUMBER,
	"CLUSTER_WAIT_TIME" NUMBER,
	"USER_IO_WAIT_TIME" NUMBER,
	"ELAPSED_TIME" NUMBER,
	"ELAPSED_TIME/EXECUTIONS" NUMBER,
	"HOST_NAME" VARCHAR2(64) NOT NULL ENABLE,
	"INSTANCE_NAME" VARCHAR2(4000) NOT NULL ENABLE,
	CONSTRAINT "ORAMON_TOP_SQL_PK" PRIMARY KEY ("SNAP_ID","HOST_NAME","INSTANCE_NAME")
  USING INDEX
  PCTFREE 10 INITRANS 2 MAXTRANS 164 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"