  CREATE TABLE "ORAMON"."ORAMON_SGA_MEMORY" 
   (	"SNAP_ID" NUMBER NOT NULL ENABLE,
	"SNAP_TIME" DATE NOT NULL ENABLE,
	"NAME" VARCHAR2(64) NOT NULL ENABLE,
	"BVAL" NUMBER NOT NULL ENABLE,
	"HOST_NAME" VARCHAR2(64) NOT NULL ENABLE,
	"INSTANCE_NAME" VARCHAR2(4000) NOT NULL ENABLE,
	CONSTRAINT "ORAMON_SGA_MEMORY_PK" PRIMARY KEY ("SNAP_ID","SNAP_TIME","NAME")
  USING INDEX
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"