  CREATE TABLE "ORAMON"."ORAMON_TOP_SQLS" 
   (	"INSTANCE_NUMBER" NUMBER NOT NULL ENABLE,
	"DBID" NUMBER NOT NULL ENABLE,
	"B_SNAP_ID" NUMBER NOT NULL ENABLE,
	"E_SNAP_ID" NUMBER NOT NULL ENABLE,
	"B_SNAP_TIME" DATE NOT NULL ENABLE,
	"E_SNAP_TIME" DATE NOT NULL ENABLE,
	"INTERVAL_MIN" NUMBER,
	"DBTIMEMIN" NUMBER,
	"AAS" NUMBER,
	"HV" NUMBER,
	"ELAPSED_TIME_SEC" NUMBER,
	"EXECUTIONS" NUMBER,
	"ELAPSED_PER_EXEC_SEC" NUMBER,
	"PERCENT_OF_DBTIME_USED" NUMBER,
	"CPU_TIME_SEC" NUMBER,
	"CPU_TIME_MS_PER_EXEC" NUMBER,
	"PHYSICAL_READS" NUMBER,
	"PHYSICAL_READS_PER_EXECUTION" NUMBER,
	"BUFFER_GETS" NUMBER,
	"GETS_PER_EXECUTION" NUMBER,
	"ROWS_PROCESSED" NUMBER,
	"ROWS_PROCESSED_PER_EXECUTION" NUMBER,
	"PARSE_CALLS" NUMBER,
	"MAX_SHARABLE_MEM_KB" NUMBER,
	"LAST_SHARABLE_MEM_KB" NUMBER,
	"MAX_VERSION_COUNT" NUMBER,
	"LAST_VERSION_COUNT" NUMBER,
	"DELTA_VERSION_COUNT" NUMBER,
	"CLUSTER_WAIT_TIME_SEC" NUMBER,
	"CWT_PERCENT_OF_ELAPSED_TIME" NUMBER,
	"AVG_HARD_PARSE_TIME_MS" NUMBER,
	"MODULE" VARCHAR2(64),
	"SQL_TEXT" VARCHAR2(256),
	"EVENT_NAME" VARCHAR2(17) NOT NULL ENABLE,
	"INSTANCE_NAME" VARCHAR2(4000) NOT NULL ENABLE,
	"HOST_NAME" VARCHAR2(64) NOT NULL ENABLE,
	CONSTRAINT "ORAMON_TOP_SQLS_PK" PRIMARY KEY ("INSTANCE_NUMBER","DBID","B_SNAP_ID","E_SNAP_ID","B_SNAP_TIME","E_SNAP_TIME","EVENT_NAME","INSTANCE_NAME","HOST_NAME")
  USING INDEX
  PCTFREE 10 INITRANS 2 MAXTRANS 159 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"