  CREATE TABLE "ORAMON"."ORAMON_DB" 
   (	"ENVIRONMENT_NAME" VARCHAR2(80) NOT NULL ENABLE,
	"HOSTNAME" VARCHAR2(80) NOT NULL ENABLE,
	"DB_LINK_NAME" VARCHAR2(80) NOT NULL ENABLE,
	"DEFAULTDB" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	CONSTRAINT "ORAMON_DB_CHK1" CHECK ((DEFAULTDB in ('Y', 'N'))) ENABLE,
	CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ENVIRONMENT_NAME")
  USING INDEX
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"