REM
REM Schema and workspace for ORAMON app
REM Install in client database where APEX is installed
REM

DECLARE
  lv_count number := 0;
BEGIN

  SELECT COUNT(*)
  INTO lv_count
  FROM DBA_USERS
  WHERE USERNAME = 'ORAMON';

  IF lv_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP USER ORAMON CASCADE';
  END IF;

END;
/

CREATE USER "ORAMON" IDENTIFIED BY "oracle"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "ORAMON" QUOTA UNLIMITED ON "USERS";

-- ROLES

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO "ORAMON" ;
GRANT CREATE TRIGGER TO "ORAMON" ;
GRANT CREATE MATERIALIZED VIEW TO "ORAMON" ;
GRANT CREATE DIMENSION TO "ORAMON" ;
GRANT CREATE OPERATOR TO "ORAMON" ;
GRANT CREATE INDEXTYPE TO "ORAMON" ;
GRANT CREATE VIEW TO "ORAMON" ;
GRANT CREATE SESSION TO "ORAMON" ;
GRANT CREATE TABLE TO "ORAMON" ;
GRANT CREATE TYPE TO "ORAMON" ;
GRANT CREATE SYNONYM TO "ORAMON" ;
GRANT CREATE SEQUENCE TO "ORAMON" ;
--GRANT EXECUTE DYNAMIC MLE TO "ORAMON" ;
GRANT CREATE CLUSTER TO "ORAMON" ;
GRANT CREATE PROCEDURE TO "ORAMON" ;
GRANT CREATE DATABASE LINK TO "ORAMON";

-- grants
--

-- profile
--
create profile ORAMON_DEFAULT_PROFILE LIMIT PASSWORD_LIFE_TIME UNLIMITED;
alter user ORAMON profile F1_DEFAULT_PROFILE;
